/**
 * Camera Toolbox API
 * Control any camera from unified API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CameraInfo {
  
  @SerializedName("displayName")
  private String displayName = null;
  @SerializedName("manufacturer")
  private String manufacturer = null;
  @SerializedName("cameraModel")
  private String cameraModel = null;

  /**
   * The name of the camera.
   **/
  @ApiModelProperty(value = "The name of the camera.")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   * The manufacturer of the camera.
   **/
  @ApiModelProperty(value = "The manufacturer of the camera.")
  public String getManufacturer() {
    return manufacturer;
  }
  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }

  /**
   * The camera model.
   **/
  @ApiModelProperty(value = "The camera model.")
  public String getCameraModel() {
    return cameraModel;
  }
  public void setCameraModel(String cameraModel) {
    this.cameraModel = cameraModel;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CameraInfo cameraInfo = (CameraInfo) o;
    return (this.displayName == null ? cameraInfo.displayName == null : this.displayName.equals(cameraInfo.displayName)) &&
        (this.manufacturer == null ? cameraInfo.manufacturer == null : this.manufacturer.equals(cameraInfo.manufacturer)) &&
        (this.cameraModel == null ? cameraInfo.cameraModel == null : this.cameraModel.equals(cameraInfo.cameraModel));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.manufacturer == null ? 0: this.manufacturer.hashCode());
    result = 31 * result + (this.cameraModel == null ? 0: this.cameraModel.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CameraInfo {\n");
    
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  manufacturer: ").append(manufacturer).append("\n");
    sb.append("  cameraModel: ").append(cameraModel).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
