/**
 * Camera Toolbox API
 * Control any camera from unified API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CameraSettings {
  
  @SerializedName("captureMode")
  private Integer captureMode = null;
  @SerializedName("exposureMode")
  private String exposureMode = null;
  @SerializedName("aperture")
  private String aperture = null;
  @SerializedName("shutterSpeed")
  private String shutterSpeed = null;
  @SerializedName("iso")
  private String iso = null;
  @SerializedName("isoAuto")
  private Boolean isoAuto = null;
  @SerializedName("focusMetering")
  private String focusMetering = null;
  @SerializedName("focusMode")
  private String focusMode = null;

  /**
   * capture mode (0 = photo, 1 = video)
   **/
  @ApiModelProperty(value = "capture mode (0 = photo, 1 = video)")
  public Integer getCaptureMode() {
    return captureMode;
  }
  public void setCaptureMode(Integer captureMode) {
    this.captureMode = captureMode;
  }

  /**
   * The exposure mode to set
   **/
  @ApiModelProperty(value = "The exposure mode to set")
  public String getExposureMode() {
    return exposureMode;
  }
  public void setExposureMode(String exposureMode) {
    this.exposureMode = exposureMode;
  }

  /**
   * The aperture to set
   **/
  @ApiModelProperty(value = "The aperture to set")
  public String getAperture() {
    return aperture;
  }
  public void setAperture(String aperture) {
    this.aperture = aperture;
  }

  /**
   * The shutterspeed to set
   **/
  @ApiModelProperty(value = "The shutterspeed to set")
  public String getShutterSpeed() {
    return shutterSpeed;
  }
  public void setShutterSpeed(String shutterSpeed) {
    this.shutterSpeed = shutterSpeed;
  }

  /**
   * The iso sensitivity to set
   **/
  @ApiModelProperty(value = "The iso sensitivity to set")
  public String getIso() {
    return iso;
  }
  public void setIso(String iso) {
    this.iso = iso;
  }

  /**
   * Set to true to activate auto iso
   **/
  @ApiModelProperty(value = "Set to true to activate auto iso")
  public Boolean getIsoAuto() {
    return isoAuto;
  }
  public void setIsoAuto(Boolean isoAuto) {
    this.isoAuto = isoAuto;
  }

  /**
   * The current focus metering
   **/
  @ApiModelProperty(value = "The current focus metering")
  public String getFocusMetering() {
    return focusMetering;
  }
  public void setFocusMetering(String focusMetering) {
    this.focusMetering = focusMetering;
  }

  /**
   * The current focus mode
   **/
  @ApiModelProperty(value = "The current focus mode")
  public String getFocusMode() {
    return focusMode;
  }
  public void setFocusMode(String focusMode) {
    this.focusMode = focusMode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CameraSettings cameraSettings = (CameraSettings) o;
    return (this.captureMode == null ? cameraSettings.captureMode == null : this.captureMode.equals(cameraSettings.captureMode)) &&
        (this.exposureMode == null ? cameraSettings.exposureMode == null : this.exposureMode.equals(cameraSettings.exposureMode)) &&
        (this.aperture == null ? cameraSettings.aperture == null : this.aperture.equals(cameraSettings.aperture)) &&
        (this.shutterSpeed == null ? cameraSettings.shutterSpeed == null : this.shutterSpeed.equals(cameraSettings.shutterSpeed)) &&
        (this.iso == null ? cameraSettings.iso == null : this.iso.equals(cameraSettings.iso)) &&
        (this.isoAuto == null ? cameraSettings.isoAuto == null : this.isoAuto.equals(cameraSettings.isoAuto)) &&
        (this.focusMetering == null ? cameraSettings.focusMetering == null : this.focusMetering.equals(cameraSettings.focusMetering)) &&
        (this.focusMode == null ? cameraSettings.focusMode == null : this.focusMode.equals(cameraSettings.focusMode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.captureMode == null ? 0: this.captureMode.hashCode());
    result = 31 * result + (this.exposureMode == null ? 0: this.exposureMode.hashCode());
    result = 31 * result + (this.aperture == null ? 0: this.aperture.hashCode());
    result = 31 * result + (this.shutterSpeed == null ? 0: this.shutterSpeed.hashCode());
    result = 31 * result + (this.iso == null ? 0: this.iso.hashCode());
    result = 31 * result + (this.isoAuto == null ? 0: this.isoAuto.hashCode());
    result = 31 * result + (this.focusMetering == null ? 0: this.focusMetering.hashCode());
    result = 31 * result + (this.focusMode == null ? 0: this.focusMode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CameraSettings {\n");
    
    sb.append("  captureMode: ").append(captureMode).append("\n");
    sb.append("  exposureMode: ").append(exposureMode).append("\n");
    sb.append("  aperture: ").append(aperture).append("\n");
    sb.append("  shutterSpeed: ").append(shutterSpeed).append("\n");
    sb.append("  iso: ").append(iso).append("\n");
    sb.append("  isoAuto: ").append(isoAuto).append("\n");
    sb.append("  focusMetering: ").append(focusMetering).append("\n");
    sb.append("  focusMode: ").append(focusMode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
